---
- hosts: all
  tasks:
    - name: Updates apt packages list from repositories 
      apt: update_cache=yes

    - name: Install python2.7 
      apt: name=python2.7 state=latest

    - name: Install python-dev
      apt: name=python-dev state=latest

    - name: Install pip
      apt: name=python-pip state=latest

    - name: Install virtualenv
      apt: name=python-virtualenv state=latest

    - name: Create a virtualenv
      command: virtualenv /vagrant/.virtualenvs/nina-venv creates="/vagrant/.virtualenvs/nina-venv"

    - name: Install postgresql-devel
      apt: name=libpq-dev state=latest

    - name: Install python package requirements
      pip: requirements=/vagrant/requirements.txt virtualenv=/vagrant/.virtualenvs/nina-venv

    - name: Install python-psycopg2
      apt: name=python-psycopg2 state=latest

    - name: Install postgresql-9.3
      apt: name=postgresql-9.3 state=latest

    - name: Ensures postgresql is running
      service: name=postgresql state=started

    - name: Set up vagrant as PostgreSQL user
      postgresql_user: name=vagrant role_attr_flags=CREATEDB
      sudo_user: postgres

    - name: Create database for development
      postgresql_db: name=nina-dev owner=vagrant
      sudo_user: postgres
