---
- hosts: all
  tasks:
    - name: Updates apt packages list from repositories 
      apt: update_cache=yes

    - name: Install python3.4
      apt: name=python3.4 state=latest

    - name: Install python-dev
      apt: name=python-dev state=latest

    - name: Uninstall pip2
      apt: name=python3-pip state=absent

    - name: Install pip3
      apt: name=python3-pip state=latest

    - name: Install virtualenv
      apt: name=python-virtualenv state=latest

    - name: Create a virtualenv
      command: virtualenv /vagrant/.virtualenvs/nina-venv --distribute -p /usr/bin/python3.4 creates="/vagrant/.virtualenvs/nina-venv"

    - name: Install postgresql-devel
      apt: name=libpq-dev state=latest

    - name: Install python package requirements
      pip: requirements=/vagrant/requirements.txt virtualenv=/vagrant/.virtualenvs/nina-venv

    - name: Install python-psycopg2
      apt: name=python-psycopg2 state=latest

    - name: Install postgresql-9.3
      apt: name=postgresql-9.3 state=latest

    - name: Ensures postgresql is running
      service: name=postgresql state=started

    - name: Enable postgresql external connections
      lineinfile: dest=/etc/postgresql/9.3/main/pg_hba.conf line="host all all 0.0.0.0/32 trust"
      lineinfile: dest=/etc/postgresql/9.3/main/postgresql.conf regexp="^listen_addresses*" line="listen_addresses '*'"
      notify:
        - restart postgresql

    - name: Set up vagrant as PostgreSQL user
      postgresql_user: name=vagrant role_attr_flags=CREATEDB
      sudo_user: postgres

    - name: Create database for development
      postgresql_db: name=nina-dev owner=vagrant
      sudo_user: postgres

    - name: Ensure user nina-dev has access to database nina-dev
      postgresql_user: db=nina-dev name=nina-dev password=nina priv=ALL
      sudo_user: postgres

    - name: Create database for testings
      postgresql_db: name=nina-test owner=vagrant
      sudo_user: postgres

    - name: Ensure user nina-dev has access to database nina-dev
      postgresql_user: db=nina-test name=nina-test password=nina priv=ALL
      sudo_user: postgres

    - name: Chdir to project directory
      lineinfile: dest=/home/vagrant/.bashrc line="source /vagrant/.virtualenvs/nina-venv/bin/activate && cd /vagrant"
      sudo_user: postgres

  handlers:
    - name: restart postgresql
      service: name=postgresql state=restarted